# Generated by Django 5.1.4 on 2024-12-24 03:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addToDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.TextField(verbose_name='Add ToDO')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('todo_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.todolist')),
            ],
        ),
    ]
