# Generated by Django 5.1.4 on 2025-01-02 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_todolist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtodo',
            name='todo_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='api.todolist'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='auther',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
