# Generated by Django 5.1.4 on 2025-01-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_addtodo_todo_tag_alter_todolist_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtodo',
            name='checklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolist',
            name='checklist',
            field=models.BooleanField(default=False),
        ),
    ]
