# Generated by Django 5.1.5 on 2025-01-31 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_addtodo_checklist_todolist_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtodo',
            name='todo_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.todolist'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='auther',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
