# Generated by Django 5.1.5 on 2025-01-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_addtodo_todo_tag_alter_todolist_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(default='https://api.dicebear.com/7.x/identicon/svg?seed=default'),
        ),
    ]
