# Generated by Django 5.1.6 on 2025-02-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_library_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='goal',
            field=models.TextField(blank=True, verbose_name='goal'),
        ),
    ]
