# Generated by Django 5.1.6 on 2025-02-17 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_library_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=256, unique=True)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='api.library')),
            ],
        ),
    ]
