# Generated by Django 5.1.6 on 2025-02-25 06:47

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_linrary_librarytodo_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarytodo',
            name='auther',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HeaderToDO作者', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LibraryAddToDO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('todo', models.TextField(verbose_name='ADD-Lib-todo')),
                ('checklist', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 25, 6, 47, 39, 467036, tzinfo=datetime.timezone.utc))),
                ('auther', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AddToDO作者', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LibraryToDOのタグ', to='api.librarytodo')),
            ],
        ),
    ]
