# Generated by Django 5.1.6 on 2025-02-27 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_librarytodo_auther_libraryaddtodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarytodo',
            old_name='library',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='libraryaddtodo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 5, 47, 58, 13305, tzinfo=datetime.timezone.utc)),
        ),
    ]
