# Generated by Django 5.1.7 on 2025-03-08 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_library_librarytodo_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryaddtodo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
