# Generated by Django 5.1.7 on 2025-03-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_libraryaddtodo_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='code_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
