# Generated by Django 5.1.7 on 2025-03-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_first_name_customuser_code_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtodo',
            name='todo',
            field=models.TextField(max_length=1080, verbose_name='Add ToDO'),
        ),
        migrations.AlterField(
            model_name='library',
            name='goal',
            field=models.TextField(blank=True, max_length=1080, verbose_name='goal'),
        ),
        migrations.AlterField(
            model_name='libraryaddtodo',
            name='todo',
            field=models.TextField(max_length=1080, verbose_name='ADD-Lib-todo'),
        ),
        migrations.AlterField(
            model_name='librarytodo',
            name='todo',
            field=models.TextField(max_length=1080, verbose_name='task'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todo',
            field=models.TextField(max_length=1080, verbose_name='ToDO'),
        ),
    ]
