FROM node:18
RUN apt-get update && apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /frontend
COPY ./package*.json ./
RUN npm install @nuxtjs/axios
RUN npm install
COPY ./ .
EXPOSE 3000
RUN npm run build 
CMD [ "npm", "run", "start" ] 