FROM python:3.12
RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /backend
COPY . /backend/
COPY requirements.txt /backend/
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache -r requirements.txt
# RUN python manage.py collectstatic 
CMD [ "gunicorn", "config.wsgi.application", "--bind", "0.0.0.0:8000" ]